### ISSUE TITLE
Error running black_nb

### ISSUE THREAD

**Issue by chauhankaranraj** [aicoe-aiops/project-template#37]
**Describe the bug**
Running precommit with the config in this repo throws an error `AttributeError: module 'black' has no attribute 'PY36_VERSIONS'`. 

**To Reproduce**
1. Create a repo with this template
2. Run `pre-commit run --all-files`
3. See error

**Expected behavior**
black_nb runs without errors

**Screenshots**
![Screenshot from 2021-06-17 11-05-38](https://user-images.githubusercontent.com/15005500/122424193-84fc4c00-cf5c-11eb-838f-6d1571acdc8e.png)

**Additional context**
This seems like the same error as seen before [here](https://github.com/aicoe-aiops/ocp-ci-analysis/pull/199#issuecomment-827072810) and addressed in aicoe-aiops/ocp-ci-analysis#246. So maybe the same fix i.e. aicoe-aiops/ocp-ci-analysis#247 should be applied here too?

**Comment by harshad16** [comment]
The version v0.5.0 has been fixed with this solution.
